// Layout Type
export const SET_LOADER="SET_LOADER"

// Users Type
export const SET_WALLET_TYPE = "SET_WALLET_TYPE"
export const SET_WALLET = "SET_WALLET"
export const SET_BINANCE_DISCONNECTED = "SET_BINANCE_DISCONNECTED"
export const SET_METAMASK_DISCONNECTED = "SET_METAMASK_DISCONNECTED"
export const SET_METAMASK_WALLET = "SET_METAMASK_WALLET"

// Miner data
export const SET_CONTRACT_BALANCE="SET_CONTRACT_BALANCE"
export const SET_USER_BALANCE="SET_USER_BALANCE"
export const SET_ALLOWANCE="SET_ALLOWANCE"
export const SET_MY_MINERS="SET_MY_MINERS"
export const SET_DIGGING_PER_HOUR="SET_DIGGING_PER_HOUR"
export const SET_SELL_EXAMPLE="SET_SELL_EXAMPLE"
export const SET_SELL_PRICE="SET_SELL_PRICE"
export const SET_SECONDS_UNTIL_FULL="SET_SECONDS_UNTIL_FULL"